#!/bin/bash

set -e -x

REPOS="
  github.com/cloudfoundry-incubator/inigo
  github.com/cloudfoundry-incubator/auctioneer
  github.com/cloudfoundry-incubator/route-emitter
  github.com/cloudfoundry/gorouter
  github.com/cloudfoundry-incubator/executor
  github.com/cloudfoundry-incubator/converger
  github.com/cloudfoundry-incubator/rep
  github.com/cloudfoundry-incubator/stager
  github.com/cloudfoundry-incubator/nsync
  github.com/cloudfoundry-incubator/file-server
  github.com/cloudfoundry-incubator/linux-circus
  github.com/cloudfoundry-incubator/warden-linux
  github.com/cloudfoundry-incubator/tps
"

LOGGREGATOR_PATH=${LOGGREGATOR_PATH:-~/workspace/loggregator}
BUILD_DIR=${BUILD_DIR:-/tmp/inigo}

SCRIPTS_DIR=$(cd $(dirname $0) && pwd)
mkdir -p ${BUILD_DIR}

cp $SCRIPTS_DIR/.drone.yml ${BUILD_DIR}/
cp $SCRIPTS_DIR/build.yml ${BUILD_DIR}/

# make sure we have all our dependencies (any version)
go get $(for repo in $REPOS; do echo -n " $repo/..."; done)

# check that the tests compile
pushd $(dirname $SCRIPTS_DIR)
  go test -c
  rm inigo.test
popd

pushd $BUILD_DIR
  # pull dependent packages into the temporary gopath, using godep so that
  # it'll only fetch the packages that are used (not entire repos)
  godep save $(for repo in $REPOS; do echo -n " $repo/..."; done)
  rsync --del --exclude '.*' -a Godeps/_workspace/src/ src/
  rm -rf Godeps

  function copy_to_gopath {
    mkdir -p ${BUILD_DIR}/src/${1}
    rsync --del --exclude '.*' --exclude '*.test' -a ${GOPATH}/src/${1}/ ${BUILD_DIR}/src/${1}/
  }

  # grab and set up our components
  for package in $REPOS; do
    copy_to_gopath $package &
  done

  # install application dependencies
  for package in github.com/coreos/etcd github.com/apcera/gnatsd; do
    copy_to_gopath $package &
  done

  rsync --del --exclude '.*' -a ${LOGGREGATOR_PATH} ${BUILD_DIR}/loggregator/ &

  wait

  if [ -n "$GLIDER_URL" ]; then
    fly -- bogus-argv-0 "$@"
  else
    drone -privileged build
  fi
popd
