#!/bin/bash

set -e -x

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

pushd $FIRST_GOPATH/src/github.com/cloudfoundry-incubator/warden-linux
  make # compile wshd/etc.
  export WARDEN_BINPATH=$PWD/linux_backend/bin
popd

go install github.com/onsi/ginkgo/ginkgo

export WARDEN_ROOTFS=/opt/warden/rootfs

pushd $FIRST_GOPATH/src/github.com/cloudfoundry-incubator/inigo
  if [ "$GINKGO_PARALLEL" = "true" ]; then
    ginkgo -r -failOnPending -randomizeAllSpecs -nodes=4 -stream -race -slowSpecThreshold=10 "$@"
  else
    ginkgo -r -failOnPending -randomizeAllSpecs -race -slowSpecThreshold=10 "$@"
  fi
popd
