#!/bin/bash

set -e -x

apt-get install aufs-tools

pushd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/warden-linux
  make # compile wshd/etc.
  export WARDEN_BINPATH=$PWD/linux_backend/bin
popd

go install github.com/onsi/ginkgo/ginkgo

export WARDEN_ROOTFS=/opt/warden/rootfs

# used for routing to apps; same logic that Warden uses.
export EXTERNAL_ADDRESS=$(ip route get 8.8.8.8 | sed 's/.*src\s\(.*\)\s/\1/;tx;d;:x')

# set up a $TMPDIR so warden's graphs go onto tmpfs
mkdir -p /tmp/warden-tmp
mount -t tmpfs -o size=2G none /tmp/warden-tmp
export WARDEN_GRAPH_PATH=/tmp/warden-tmp

color_flag=""
if [ -n "$GO_PIPELINE_COUNTER" ]; then
  color_flag="-noColor"
fi

nodes_flag=""
if [ "$GINKGO_PARALLEL" = "true" ]; then
  nodes_flag="-nodes=4"
fi

pushd $GOPATH_ROOT/src/github.com/cloudfoundry-incubator/inigo
  ginkgo $color_flag $nodes_flag -r -failOnPending -randomizeAllSpecs -trace -race -slowSpecThreshold=10 "$@"
popd
