#!/bin/bash

set -e -x

if [ -z "$WORKSPACE" ]; then
  echo "This script assumes it's running in Jenkins."
  echo "You probably want to just run 'ginkgo'."
  exit 1
fi

. /usr/local/share/gvm/scripts/gvm
gvm use go1.2

export GOPATH=$WORKSPACE/go
export PATH=$GOPATH/bin:$PATH

source_root=$GOPATH/src/github.com/cloudfoundry-incubator/inigo

pushd $GOPATH
  git clone https://github.com/cloudfoundry-incubator/diego-workspace
  cp ./diego-workspace/Cartridge.lock $source_root
popd

go get -v github.com/vito/gocart

pushd $source_root
  gocart
popd

pushd $GOPATH/src/github.com/pivotal-cf-experimental/garden
  make # compile wshd/etc.
  export GARDEN_ROOT=$PWD/root
popd

go install github.com/pivotal-cf-experimental/garden
go install github.com/apcera/gnatsd

ROOTFS_FN=lucid64.dev.tgz
ROOTFS_URI=http://cfstacks.s3.amazonaws.com/${ROOTFS_FN}
ROOTFS_SHA=b2633b2ab4964f91402bb2d889f2f12449a8b828

ROOTFS_INSTALL_DIR=$WORKSPACE

mkdir -p "$ROOTFS_INSTALL_DIR"

pushd "$ROOTFS_INSTALL_DIR"
  echo "${ROOTFS_SHA}  ${ROOTFS_FN}" > checksum

  if [ ! -f ${ROOTFS_FN} ] || ! shasum -s -c checksum; then
    wget "${ROOTFS_URI}"
  fi

  mkdir -p ./rootfs
  sudo tar zxf ${ROOTFS_FN} -C ./rootfs
popd

pushd $GOPATH/src/github.com/coreos/etcd
  ./build
  cp bin/etcd $GOPATH/bin
popd

export GARDEN_ROOTFS="${ROOTFS_INSTALL_DIR}/rootfs"

go install github.com/onsi/ginkgo/ginkgo

pushd $GOPATH/src/github.com/cloudfoundry-incubator/inigo
  ginkgo -r -i -skipMeasurements -randomizeAllSpecs "$@"
popd
