#!/bin/bash

set -e -x

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

pushd $FIRST_GOPATH/src/github.com/pivotal-cf-experimental/garden
  make # compile wshd/etc.
  export GARDEN_ROOT=$PWD/root
popd

go install github.com/onsi/ginkgo/ginkgo

ROOTFS_FN=lucid64.dev.tgz
ROOTFS_URI=http://cfstacks.s3.amazonaws.com/${ROOTFS_FN}
ROOTFS_SHA=b2633b2ab4964f91402bb2d889f2f12449a8b828

ROOTFS_INSTALL_DIR=$WORKSPACE

mkdir -p "$ROOTFS_INSTALL_DIR"

pushd "$ROOTFS_INSTALL_DIR"
  echo "${ROOTFS_SHA}  ${ROOTFS_FN}" > checksum

  if [ ! -f ${ROOTFS_FN} ] || ! shasum -s -c checksum; then
    wget "${ROOTFS_URI}"
  fi

  mkdir -p ./rootfs
  sudo tar zxf ${ROOTFS_FN} -C ./rootfs
popd

export GARDEN_ROOTFS="${ROOTFS_INSTALL_DIR}/rootfs"

pushd $FIRST_GOPATH/src/github.com/cloudfoundry-incubator/inigo
  ginkgo -r -failOnPending -randomizeAllSpecs "$@"
popd
